# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Antonio Trenta
# Description of the Site
description: Data Scientist
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://live.staticflickr.com/7722/17117350128_d5511a1718_k.jpg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: antoniotrenta.ds@gmail.com
facebook_username:
twitter_username: antosanshi
instagram_username: antoniotre86
linkedin_username: antonio-trenta
github_username:  antoniotre86
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: Antonio Trenta
# URL for the Image of the Author
author-image: /assets/images/picrew_me-00.png
# 60 Words About the Author
author-about: I'm a Data Scientist, educated in Stats and ML, working in the field since 2013. I have an undergraduate degree in Economics, a graduate degree in Statistics, and a MSc in Machine Learning and Computational Statistics. Learned to code on the job; mainly Python, R and Scala. I've worked on natural language processing and information extraction, recommender systems, web user behaviour modelling and personalisation for e-commerce, product analytics, forecasting, reporting, BOT and anomaly detection in web sessions, user representation and profiling.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/antoniotre86

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
